//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOnline.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Comments = new HashSet<Comment>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }

        public int IdProduct { get; set; }

        [Required(ErrorMessage = "Name Food is required!")]
        [RegularExpression(@"\S+.*", ErrorMessage = "Name food must not contain a leading space!")]
        public string NameProduct { get; set; }
        public int IdCategory { get; set; }

        //[Required(ErrorMessage = "/*Create food fail, image not correct!*/")]
        //[Display(Name = "Enter your email"), Required]
        public string Img { get; set; }

        [Required(ErrorMessage = "Price is required!")]
        [Range(0, 9999999999999.99, ErrorMessage = "Please enter the correct price! ")]
        [DisplayFormat(DataFormatString = "{0:0,0}")]
        public decimal Price { get; set; }

        [RegularExpression(@"\S+.*", ErrorMessage = "Describe must not contain a leading space!")]
        public string Describe { get; set; }

        [DisplayFormat(DataFormatString = "{0:0,0}")]
        [Range(0, 9999999999999.99, ErrorMessage = "Please enter a value bigger than 0! ")]
        public Nullable<decimal> Promotion { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy hh:mm}")]
        public Nullable<System.DateTime> StartTimePromotion { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy hh:mm}")]
        public Nullable<System.DateTime> EndTimePromotion { get; set; }
        public Nullable<bool> IsDelete { get; set; }

        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
